spring:
  application:
    name: bancoias

  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  sql:
    init:
      mode: never

  flyway:
    enabled: true
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    locations: classpath:db/migration/postgresql

management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    root: INFO
    com.maycol.bancoias: DEBUG
    org.springframework.r2dbc: DEBUG
    org.springframework.transaction: DEBUG