spring:
  application:
    name: bancoias

  r2dbc:
    url: ${DATABASE_R2DBC_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  sql:
    init:
      mode: never

  flyway:
    enabled: true
    url: ${DATABASE_MIGRATION_JDBC_URL}
    user: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    locations: classpath:db/migration/postgresql

management:
  endpoints:
    web:
      exposure:
        include: health